jwt:
  access:
    token:
      expiration:
        seconds: 3600 #60m
  refresh:
    token:
      expiration:
        seconds: 604800 #7-day
  token:
    secret-key: itsepguyitsepguyitsepgyitsitsits

# DB
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/omokwang?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: update