jwt:
  access:
    token:
      expiration:
        seconds: 3600
  refresh:
    token:
      expiration:
        seconds: 604800
  token:
    secret-key: itsepguyitsepguyitsepgyitsitsits

# DB
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/omokwang?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root1234
