jwt:
  access:
    token:
      expiration:
        seconds: 3600 #60m
  refresh:
    token:
      expiration:
        seconds: 604800 #7-day
  token:
    secret-key: ${JWT_SECRET_KEY}

# DB
spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update